Make record data non-nullable
Qualifyze/airtable pull request #73
Opened 2021-08-02 09:10 UTC by vubogovich

## What

Make `AirtableRecord.data` non-nullable.

## Why

`AirtableRecord.data` is always an object once any operation is executed and it's inconvenient to cast it to non-nullable in the calling code.

## How

Add a base class `AirtableRecordDraft` which contains the record id and not the data.

## Testing

```
npm run integration
```

## Who is affected

Breaking change as `data` argument of `AirtableRecord` constructor is now required.

## Remarks

`AirtableRecordDraft` might give an idea that it holds the data and it's just not saved yet. Though I'm not sure what name would be better. As an option we could consider removing the usage of `AirtableRecord` operations from `Table` class instead of the intermediate class.

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualifyze/airtable/73)

2021-08-02 12:17 UTC, gregoralbrecht requested changes
> *[Reviewable](https://reviewable.io/reviews/qualifyze/airtable/73)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @gsuess and @vubogovich)

___
*[package.json, line 3 at r1](https://reviewable.io/reviews/qualifyze/airtable/73#-Mg5mpOnDDKwBlBRFP44:-Mg5mpOnDDKwBlBRFP45:bxhtp2v) ([raw file](https://github.com/qualifyze/airtable/blob/cd8c4837dec111ae2949476988ca2929934bfbb0/package.json#L3)):*
> ```JSON
> {
>   "name": "@qualifyze/airtable",
>   "version": "2.0.0",
> ```

I'd be curious to hear and @gsuess 's opinions on whether we should keep version bumps in separate PRs. Personally, I see value in it, because it let's us revert changes without reverting the version bump (which doesn't make sense). 


<!-- Sent from Reviewable.io -->

2021-08-02 13:37 UTC, vubogovich reviewed
> *[Reviewable](https://reviewable.io/reviews/qualifyze/airtable/73)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @gsuess)

___
*[package.json, line 3 at r1](https://reviewable.io/reviews/qualifyze/airtable/73#-Mg5mpOnDDKwBlBRFP44:-Mg63nYi7G96Y6wCWz0x:b-ue1fk9) ([raw file](https://github.com/qualifyze/airtable/blob/cd8c4837dec111ae2949476988ca2929934bfbb0/package.json#L3)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

I'd be curious to hear and @gsuess 's opinions on whether we should keep version bumps in separate PRs. Personally, I see value in it, because it let's us revert changes without reverting the version bump (which doesn't make sense). 
</blockquote></details>

In my opinion, either we bump version in PR itself or should switch the way we publish to GitHub releases where version is coming from GitHub UI.


<!-- Sent from Reviewable.io -->

2021-08-03 12:30 UTC, gsuess requested changes
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/airtable/73)* status: all files reviewed, 2 unresolved discussions (waiting on @gregoralbrecht and @vubogovich)

___
*[package.json, line 3 at r1](https://reviewable.io/reviews/qualifyze/airtable/73#-Mg5mpOnDDKwBlBRFP44:-MgAyvJu8ryMOjRQrgbN:b-g5ntfv) ([raw file](https://github.com/qualifyze/airtable/blob/cd8c4837dec111ae2949476988ca2929934bfbb0/package.json#L3)):*
<details><summary><i>Previously, vubogovich (Vladimir Ubogovich) wrote…</i></summary><blockquote>

In my opinion, either we bump version in PR itself or should switch the way we publish to GitHub releases where version is coming from GitHub UI.
</blockquote></details>

Changing the version in the same PR is dangerous as a conflict can cause inadvertent version downgrades. 

However changing it in a separate PR is also dangerous as you can be releasing patch versions with breaking changes because PR with breaking changes was merged earlier than expected.

So I think both models are flawed - therefore I am indifferent here.
___
*[src/record.ts, line 23 at r1](https://reviewable.io/reviews/qualifyze/airtable/73#-MgAyj7cCyfQFy4OBShe:-MgAyj7d3f8dHmi3en6O:bj78re5) ([raw file](https://github.com/qualifyze/airtable/blob/cd8c4837dec111ae2949476988ca2929934bfbb0/src/record.ts#L23)):*
> ```XML
> }
> 
> export class AirtableRecordDraft<Fields extends UnknownFields>
> ```

should move to separate file. 


<!-- Sent from Reviewable.io -->

2021-08-03 16:39 UTC, vubogovich reviewed
> *[Reviewable](https://reviewable.io/reviews/qualifyze/airtable/73)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @gregoralbrecht and @gsuess)

___
*[package.json, line 3 at r1](https://reviewable.io/reviews/qualifyze/airtable/73#-Mg5mpOnDDKwBlBRFP44:-MgBsSU-2l5quV5IjBAG:b-896fix) ([raw file](https://github.com/qualifyze/airtable/blob/cd8c4837dec111ae2949476988ca2929934bfbb0/package.json#L3)):*
<details><summary><i>Previously, gsuess (Garik Suess) wrote…</i></summary><blockquote>

Changing the version in the same PR is dangerous as a conflict can cause inadvertent version downgrades. 

However changing it in a separate PR is also dangerous as you can be releasing patch versions with breaking changes because PR with breaking changes was merged earlier than expected.

So I think both models are flawed - therefore I am indifferent here.
</blockquote></details>

Done.
___
*[src/record.ts, line 23 at r1](https://reviewable.io/reviews/qualifyze/airtable/73#-MgAyj7cCyfQFy4OBShe:-MgBsUHc-42HuqGaSN57:b-896fix) ([raw file](https://github.com/qualifyze/airtable/blob/cd8c4837dec111ae2949476988ca2929934bfbb0/src/record.ts#L23)):*
<details><summary><i>Previously, gsuess (Garik Suess) wrote…</i></summary><blockquote>

should move to separate file. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-04 11:33 UTC, gregoralbrecht reviewed
> *[Reviewable](https://reviewable.io/reviews/qualifyze/airtable/73)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @gsuess)

___
*[package.json, line 3 at r1](https://reviewable.io/reviews/qualifyze/airtable/73#-Mg5mpOnDDKwBlBRFP44:-MgFuxgX-0q_zLb8zBFF:b-uf6m76) ([raw file](https://github.com/qualifyze/airtable/blob/cd8c4837dec111ae2949476988ca2929934bfbb0/package.json#L3)):*
> dangerous as you can be releasing patch versions with breaking changes because PR with breaking changes was merged earlier than expected.

Interesting point! That's exactly why I love Changesets :heart_eyes: Each PR contains the appropriate version increment (whether it's a patch, minor, or major) and the release will never be e.g. a patch with minor changes


<!-- Sent from Reviewable.io -->

2021-08-04 12:05 UTC, vubogovich reviewed
> *[Reviewable](https://reviewable.io/reviews/qualifyze/airtable/73)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @gsuess)

___
*[package.json, line 3 at r1](https://reviewable.io/reviews/qualifyze/airtable/73#-Mg5mpOnDDKwBlBRFP44:-MgG0Sfr-YasHF_0Cgv_:b-9t311w) ([raw file](https://github.com/qualifyze/airtable/blob/cd8c4837dec111ae2949476988ca2929934bfbb0/package.json#L3)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

> dangerous as you can be releasing patch versions with breaking changes because PR with breaking changes was merged earlier than expected.

Interesting point! That's exactly why I love Changesets :heart_eyes: Each PR contains the appropriate version increment (whether it's a patch, minor, or major) and the release will never be e.g. a patch with minor changes
</blockquote></details>

I'm not happy you force to change the release process for airtable now but I like that changesets create a nice release on github.
Let's try - https://github.com/Qualifyze/dev-infrastructure/pull/178


<!-- Sent from Reviewable.io -->

2021-08-04 12:06 UTC, gregoralbrecht reviewed
> *[Reviewable](https://reviewable.io/reviews/qualifyze/airtable/73)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @gsuess)

___
*[package.json, line 3 at r1](https://reviewable.io/reviews/qualifyze/airtable/73#-Mg5mpOnDDKwBlBRFP44:-MgG2ZYx9bhmzP8NNUeW:btetkin) ([raw file](https://github.com/qualifyze/airtable/blob/cd8c4837dec111ae2949476988ca2929934bfbb0/package.json#L3)):*
What do you mean by:

>I'm not happy you force to change the release process for airtable now

?


<!-- Sent from Reviewable.io -->

2021-08-04 12:23 UTC, gregoralbrecht reviewed
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/airtable/73)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @gsuess)



<!-- Sent from Reviewable.io -->

2021-08-04 15:16 UTC, gsuess approved these changes
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/airtable/73)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vubogovich)



<!-- Sent from Reviewable.io -->

2021-08-04 15:32 UTC, gregoralbrecht approved these changes
> Reviewed 2 of 5 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/airtable/73)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vubogovich)



<!-- Sent from Reviewable.io -->

2021-08-04 15:36 UTC, vubogovich reviewed
> *[Reviewable](https://reviewable.io/reviews/qualifyze/airtable/73)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vubogovich)

___
*[package.json, line 3 at r1](https://reviewable.io/reviews/qualifyze/airtable/73#-Mg5mpOnDDKwBlBRFP44:-MgGn6W22c2gPhafBQf-:b-3yza5g) ([raw file](https://github.com/qualifyze/airtable/blob/cd8c4837dec111ae2949476988ca2929934bfbb0/package.json#L3)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

What do you mean by:

>I'm not happy you force to change the release process for airtable now

?
</blockquote></details>

I mean strongly encourage to change the release process but was confused that your review state was "requested changes". All good now.


<!-- Sent from Reviewable.io -->

2021-08-11 13:13 UTC, gregoralbrecht approved these changes
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/airtable/73)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vubogovich)



<!-- Sent from Reviewable.io -->

2021-08-11 13:17 UTC, merged